### ISSUE TITLE
Original CSync taken down on Thunderstore, new fork available

### ISSUE THREAD

**Issue by Fl4sHNoX** [pacoito123/LC_StoreRotationConfig#1]
As [CSync](https://github.com/Owen3H/CSync) has just been set as "deprecated" as it was taken down by its author on the Thunderstore -for reasons irrelevant to this post-, I'm simply giving you a heads-up that you can use as a new dependency for your mod a fork of the project that has been swiftly uploaded to the Thunderstore: 

Thunderstore : https://thunderstore.io/c/lethal-company/p/Sigurd/CSync/
GitHub : https://github.com/lc-sigurd/CSync

**Comment by pacoito123** [comment]
Thanks for the heads-up!

I've switched to that fork in the latest release, it should show up soon in Thunderstore/r2modman, but is available right now as a release.
