### ISSUE TITLE
[v50] [Error] Mod not loading

### ISSUE THREAD

**Issue by EpicIsGabe** [pacoito123/LC_StoreRotationConfig#2]
Attached error.
Mod not loading, tested independently of any mods except the associated dependencies. Still throwing error below.

[Info   :   BepInEx] Loading [StoreRotationConfig 1.2.0]
[Error  :StoreRotationConfig] Error while initializing 'StoreRotationConfig': System.MissingMethodException: Method not found: void CSync.Lib.SyncedInstance`1.add_SyncComplete(System.EventHandler)
  at StoreRotationConfig.Plugin.Awake () [0x0000e] in ./Plugin.cs:30

**Comment by EpicIsGabe** [comment]
![image](https://github.com/pacoito123/LC_StoreRotationConfig/assets/166662406/de9724c3-33ac-4dff-8b23-e061a1a1678b)

Full list of mods installed for testing

**Comment by pacoito123** [comment]
Currently it's not compatible with the latest versions of CSync (v4.0.0 and above), which are automatically downloaded by Thunderstore/r2modman when downloading dependencies. You need to downgrade to v3.1.1 to use this mod, but if you have another mod that _has_ to have CSync v4, I could upload a pre-release that supports it, though you would have to import it manually. Unfortunately I have to pick between either switching to v4 and breaking compatibility with older mods that have yet to update, or remain on v3 to maintain compatibility until v4 is more widely adopted.

**Comment by pacoito123** [comment]
Latest release ([v2.0.0](https://github.com/pacoito123/LC_StoreRotationConfig/releases/tag/v2.0.0)) adds support for CSync v4.1.0, though ([v1.3.0](https://github.com/pacoito123/LC_StoreRotationConfig/releases/tag/v1.3.0)) can still be used if CSync v3 is ever needed. Feel free to reopen this issue if you encounter any problems with it, though nothing came up when I was testing it earlier.
