### ISSUE TITLE
Prevents buying of ship windows

### ISSUE THREAD

**Issue by Ryyye** [pacoito123/LC_StoreRotationConfig#3]
Unsure if this is a problem that can be fixed on this mod's end, but while this mod is present, windows from the ship windows mod are unable to be bought, it doesn't seem to prevent purchasing of any other store items from other mods

**Comment by pacoito123** [comment]
Should be fixed in latest release ([v2.4.0](https://github.com/pacoito123/LC_StoreRotationConfig/releases/v2.4.0)), though let me know if there's any other issues!
